name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Start server
        run: |
          npx serve . -l 5500 &
          sleep 5

      - name: Run Jest tests
        run: npm run test:jest

      - name: Run Cypress tests
        run: npm run test:cypress
